server:
  port: 9090

spring:
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop
    username: sa
    password:
    driver-class-name: org.h2.Driver


  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show-sql: true
        format_sql: true


logging:
  level:
    org.hibernate.SQL: debug